# Generated by Django 2.2.4 on 2019-08-31 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.CharField(default='', max_length=250)),
                ('Iamge', models.ImageField(null=True, upload_to='')),
                ('Describtion', models.CharField(max_length=250)),
                ('Specialized', models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Bones', 'Bones'), ('Dentist', 'Dentist'), ('Cardiologist', 'Neurologist')], max_length=50)),
                ('Country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('Clinic_Address', models.CharField(max_length=250)),
                ('Clinic_Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Check_Value', models.CharField(max_length=50)),
                ('Period_of_wait', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctors', to='doctors_app.Doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.DateField(blank=True, null=True)),
                ('Check_times', models.TimeField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='doctors_app.Doctor')),
            ],
        ),
    ]
