# Generated by Django 2.2.4 on 2019-08-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='work_days',
        ),
    ]
