# Generated by Django 2.2.4 on 2019-09-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0002_remove_booking_work_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Days_of_work',
            field=models.DateField(blank=True, null=True),
        ),
    ]
