# Generated by Django 2.2.4 on 2019-09-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0005_auto_20190902_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doctor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_id', to='doctors_app.Doctor'),
        ),
    ]
