# Generated by Django 2.2.4 on 2019-09-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0007_auto_20190902_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Paitent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='doctors_app.Paitent'),
        ),
    ]
