# Generated by Django 2.2.4 on 2019-09-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0012_auto_20190902_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('other', 'Other')], max_length=250)),
                ('id_patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='doctors_app.Paitent')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attend', models.BooleanField()),
                ('id_patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Attendance', to='doctors_app.Paitent')),
                ('is_Booking', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Booking', to='doctors_app.Booking')),
            ],
        ),
    ]
