# Generated by Django 2.2.4 on 2019-09-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0013_attendance_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('Visa', 'Visa')], max_length=250),
        ),
    ]
